eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8085
spring:
  application:
    name: service-transaction
  data:
    mongodb:
      database: ms-customer
      uri: mongodb://bankeveris:FNDpBlkBc14SrLztrnAET3SNYYzPdtZ46AG3PiHYqP3QHlHUF0SzWkQjdMFuW8qvtwF7HswHZfvP9Ef93mK0Qw==@bankeveris.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@bankeveris@